on:
  push:
    branches: [ main ]

jobs:
  install_and_build:
    uses: ./.github/workflows/ci.yml

  deploy_docs:
    needs: install_and_build
    runs-on: ubuntu-latest
    steps:
      - name: Publish github pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/evertbouw/pulleys.git
          npx gh-pages -d docs -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
